from logging import (
  getLogger,
)

from typing import (
  Sequence,
)

from numpy import (
  zeros as np_zeros,
)

from resim.pvt.datatypes import (
  Float,
  Vector,
  SepResult,
  State,
  States,
)

from resim.pvt.utils import (
  PhaseFinder,
  findex,
)

from resim.pvt.flash import (
  FlashNpPTEos,
  FlashRoutine,
  flash,
)


logger = getLogger('sep')


def stsep(
  eos: FlashNpPTEos,
  yi: Vector[Float],
  n: float = 1.,
  P1: float = 101325.,
  P2: float = 293.15,
  init: SepResult | None = None,
  name: str = 'main',
  flashroutine: FlashRoutine = flash(),
) -> SepResult[str, States[State]]:
  """Separator of standard conditions.

  Determine a multiphase state of a mixture for a given separator
  conditions and mole composition.

  Parameters
  ----------
  eos: FlashNpPTEos
    An initialized instance of an equation of state.

  yi: Vector[Float], shape (Nc,)
    Mole fractions of `Nc` components.

  n: float
    Mole number of a mixture [mol]. Default is `1.0` [mol].

  P1: float
    The first thermodynamic parameter in SI units that characterizes
    the separation conditions. Default is standard pressure `101325.0`
    [Pa].

  P2: float
    The second thermodynamic parameter in SI units that characterizes
    the separation conditions. Default is standard temperature `273.15`
    [K].

  init: SepResult | None
    This parameter is used to initialize a flash routine. The detailed
    explanation of the logic behind different types of `init` is given
    in the following table:

    +-----------------+------------------------------------------------+
    | Type            | Description                                    |
    +=================+================================================+
    | SepResult       | A thermodynamic state at the zeroth stage of   |
    |                 | the stream (with the name `name`) is used to   |
    |                 | obtain the first initial guess of k-values.    |
    +-----------------+------------------------------------------------+
    | None            | A sequence of initial guesses of k-values is   |
    |                 | generated by a flash routine internally.       |
    +-----------------+------------------------------------------------+

    Default is `None`.

  name: str
    The name of a stream within the separator. Default is `'main'`.

  flashroutine: FlashRoutine
    A callable object that can be used to perform the multiphase flash
    calculation. Default is `flash()`.

  Returns
  -------
  Separator calculation results as an instance of `SepResult`.
  """
  guess: State | None = None
  if init is not None:
    guess = init[name][0]
  state = flashroutine(eos, P1, P2, yi, n, guess)
  res: SepResult[str, States[State]] = SepResult()
  res[name] = States([state])
  res.set_gasstate(name, 0)
  res.set_liqstate(name, 0)
  logger.debug('%r', res)
  return res


def ltsep(
  eos: FlashNpPTEos,
  yi: Vector[Float],
  n: float = 1.,
  P1s: Sequence[float] = [7e6, 4.5e6, 2e6, 101325.],
  P2s: Sequence[float] = [223.15, 238.15, 258.15, 293.15],
  init: SepResult | None = None,
  gasname: str = 'main',
  liqname: str = 'liquid',
  stagesc: int = -1,
  flashroutine: FlashRoutine = flash(),
  gasfinder: PhaseFinder = findex,
) -> SepResult[str, States[State]]:
  """Multiphase separator that can be used to simulate low-temperature
  separation.

  Parameters
  ----------
  eos: FlashNpPTEos
    An initialized instance of an equation of state.

  yi: Vector[Float], shape (Nc,)
    Mole fractions of `Nc` components.

  n: float
    Mole number of a mixture [mol]. Default is `1.0` [mol].

  P1s: Sequence[float]
    A sequence of values of the first thermodynamic parameter in
    SI units each of which characterizes the corresponding stage
    of the gas phase stream within the separator. Default is a list
    of pressures in [Pa]: `[7e6, 4.5e6, 2e6, 101325.0]`.

  P2s: Sequence[float]
    A sequence of values of the second thermodynamic parameter in
    SI units each of which characterizes the corresponding stage
    of the gas phase stream within the separator. Default is a list
    of temperatures in [K]: `[223.15, 238.15, 258.15, 293.15]`.

  init: SepResult | None
    This parameter is used to initialize a flash routine. The detailed
    explanation of the logic behind different types of `init` is given
    in the following table:

    +-----------------+------------------------------------------------+
    | Type            | Description                                    |
    +=================+================================================+
    | SepResult       | Each state of a sequence of states within the  |
    |                 | gas phase stream of the given results is used  |
    |                 | to initialize the corresponding flash routine. |
    |                 | A state of the liquid phase stream is used to  |
    |                 | initialize the corresponding flash procedure.  |
    +-----------------+------------------------------------------------+
    | None            | A sequence of initial guesses of k-values is   |
    |                 | generated by a flash routine internally.       |
    +-----------------+------------------------------------------------+

    Default is `None`.

  gasname: str
    A string defining the name of the gas phase stream within the
    low-temperature separator. The gas phase stream consists of a
    sequence of stages each of which is defined by two thermodynamic
    parameters. Default is `'main'`.

  liqname: str
    A string defining the name of the liquid phase stream within
    the low-temperature separator. The liquid phase stream consists
    of the one stage which is defined by two thermodynamic parameters
    which are the same as for the `stagesc` stage of the gas phase
    stream. Default is `'liquid'`.

  stagesc: int
    An index of the stage of the gas phase stream that defines the stock
    tank conditions, at which the liquid phase is collected. It also
    specifies the thermodynamic parameters, for which the gas and liquid
    phase properties (such as, formation volume factors, ratios, etc.)
    can be calculated by a laboratory procedure. Default is `-1` (the
    last stage).

  flashroutine: FlashRoutine
    A callable object that can be used to perform the multiphase flash
    calculation. Default is `flash()`.

  gasfinder: PhaseFinder
    A callable object that can be used to obtain the index of the gas
    phase in a given state of a mixture. Default is `findex`.

  Notes
  -----
  At each stage of the low-temperature separation process, liquid phases
  are removed into the stock tank conditions. The gas phase collected
  from previous stage is transferred to the subsequent stage. The gas
  obtained from the liquid phase under stock tank conditions is combined
  with the main gas stream. The stock tank conditions are the conditions
  specified for the stage `stagesc`.
  """
  Ns = len(P1s)
  initms: Sequence[State | None]
  initl: State | None
  if init is None:
    initms = Ns * [None]
    initl = None
  else:
    initms = init[gasname]
    initl = init[liqname][0]
  if stagesc < 0:
    stagesc = Ns + stagesc
  res: SepResult[str, States[State]] = SepResult()
  statesg: States[State] = States()
  res[gasname] = statesg
  ng = n
  ygi = yi
  ngi = ng * ygi
  nli = np_zeros(shape=(eos.Nc,))
  for s, (P1, P2, initm) in enumerate(zip(P1s, P2s, initms)):
    state = flashroutine(eos, P1, P2, ygi, ng, initm)
    statesg.append(state)
    try:
      j = gasfinder(state, 0)
      ng = state.nj[j]
      ygi = state.yji[j]
      ngi = state.nji[j]
      nli += state.ni - ngi
    except IndexError:
      nli += state.ni
      ng = 0.
      ngi = ng * ygi
    if s == stagesc:
      nl = nli.sum()
      if nl > 0.:
        yli = nli / nl
        statel = flashroutine(eos, P1, P2, yli, nl, initl)
        try:
          j = gasfinder(statel, 0)
          nsg = statel.nj[j]
          nsgi = statel.nji[j]
          ng += nsg
          ngi += nsgi
          ygi = ngi / ng
          statesg[s] = flashroutine(eos, P1, P2, ygi, ng, state)
          nl -= nsg
          nli -= nsgi
          if nl > 0.:
            yli = nli / nl
            statel = flashroutine(eos, P1, P2, yli, nl, initl)
            res[liqname] = States([statel])
        except IndexError:
          res[liqname] = States([statel])
    if ng <= 0.:
      logger.warning(
        'There is no gas at the stage #%s. The separation procedure '
        'will be stopped.', s,
      )
      break
  res.set_gasstate(gasname, stagesc)
  res.set_liqstate(liqname, 0)
  logger.debug('%r', res)
  return res
